### ISSUE TITLE
Session issue with 0.5dev

### ISSUE THREAD

**Issue by jorilallo** [flashingpumpkin/django-socialregistration#117]
It seems that there's some session bug with 0.5dev branch. Sometimes I can get login to work but most of the times I'm getting the following for both Twitter and Facebook:

Traceback (most recent call last):

File "/sites/.virtualenvs/kippt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
response = callback(request, _callback_args, *_callback_kwargs)

File "/sites/.virtualenvs/kippt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 47, in view
return self.dispatch(request, _args, *_kwargs)

File "/sites/.virtualenvs/kippt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in dispatch
return handler(request, _args, *_kwargs)

File "/sites/.virtualenvs/kippt/src/django-socialregistration/socialregistration/views.py", line 208, in get
client = request.session[self.get_client().get_session_key()]

File "/sites/.virtualenvs/kippt/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 47, in **getitem**
return self._session[key]

KeyError: 'socialreg:facebook'

**Comment by flashingpumpkin** [comment]
Looking into it

**Comment by flashingpumpkin** [comment]
It might have to do with what local url and what callback url you are using:

When starting the auth process from http://localhost:8000 and you're redirected back to http://127.0.0.1:8000, you will get a new session instead of using the old one. Need to document this.

**Comment by jorilallo** [comment]
That's it. Thanks

**Comment by bergantine** [comment]
@flashingpumpkin I'm getting this error as well, is there anything else that will cause this? Mine is not the same cause as @jorde was having. I'm seeing it only in error logs, haven't figured out how to trigger it myself. But domain should be the same coming and going.
