### ISSUE TITLE
ImproperlyConfigured: Error importing middleware middleware: "No module named middleware"

### ISSUE THREAD

**Issue by Gunio** [flashingpumpkin/django-socialregistration#118]
Just pulled from git

cd example
python manage.py runserver
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/servers/basehttp.py", line 283, in run
    self.result = application(self.environ, self.start_response)
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/handlers.py", line 68, in **call**
    return self.application(environ, start_response)
  File "/Library/Python/2.7/site-packages/django/core/handlers/wsgi.py", line 250, in **call**
    self.load_middleware()
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    raise exceptions.ImproperlyConfigured('Error importing middleware %s: "%s"' % (mw_module, e))
ImproperlyConfigured: Error importing middleware middleware: "No module named middleware"
[24/Oct/2011 15:38:25] "GET / HTTP/1.1" 500 766

Not a good start :(

**Comment by flashingpumpkin** [comment]
I can't confirm this:

```
$ cd /tmp/
$ git clone https://github.com/flashingpumpkin/django-socialregistration.git
$ cd django-socialregistration/
$ virtualenv .
$ source bin/activate
(django-socialregistration)$ python setup.py develop
(django-socialregistration)$ pip install -r requirements.txt 
(django-socialregistration)$ pip install django
(django-socialregistration)$ cd example/
(django-socialregistration)$ python manage.py runserver
Validating models...

0 errors found
Django version 1.3.1, using settings 'example.settings'
Development server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```
