### ISSUE TITLE
KeyError: 'socialreg:user' when deleting session keys

### ISSUE THREAD

**Issue by diafygi** [flashingpumpkin/django-socialregistration#132]
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 47, in view
   return self.dispatch(request, _args, *_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in dispatch
   return handler(request, _args, *_kwargs)

 File "/socialregistration/views.py", line 100, in get
   return self.generate_username_and_redirect(request, user, profile, client)

 File "/socialregistration/views.py", line 84, in generate_username_and_redirect
   self.delete_session_data(request)

 File "/socialregistration/mixins.py", line 190, in delete_session_data
   del request.session['%suser' % SESSION_KEY]

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 54, in **delitem**
   del self._session[key]
## KeyError: 'socialreg:user'

Been getting the above error occasionally when someone tries to register through facebook or twitter. It appears to be trying to delete the session key, so could we just let it pass if that key doesn't exist?

**Comment by diafygi** [comment]
I've patched my version with the following

In socialregistration/mixins.py, change lines 190-192:
FROM:

```
    del request.session['%suser' % SESSION_KEY]
    del request.session['%sprofile' % SESSION_KEY]
    del request.session['%sclient' % SESSION_KEY]
```

TO:

```
    try:
        del request.session['%suser' % SESSION_KEY]
    except KeyError:
        pass
    try:
        del request.session['%sprofile' % SESSION_KEY]
    except KeyError:
        pass
    try:
        del request.session['%sclient' % SESSION_KEY]
    except KeyError:
        pass
```
