### ISSUE TITLE
KeyError: 'access_token'KeyError

### ISSUE THREAD

**Issue by diafygi** [flashingpumpkin/django-socialregistration#134]
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 47, in view
   return self.dispatch(request, _args, *_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in dispatch
   return handler(request, _args, *_kwargs)

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/views.py", line 210, in get
   client.complete(dict(request.GET.items()))

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/clients/oauth.py", line 285, in complete
   return self.get_access_token(code=GET.get('code'))

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/clients/oauth.py", line 273, in get_access_token
   self._access_token = self._get_access_token(code, **params)['access_token']

KeyError: 'access_token'

 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.7 (KHTML, like Gecko) Chrome/16.0.912.63 Safari/535.7',

**Comment by diafygi** [comment]
Another recent example:

Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/newrelic-1.0.5.156/newrelic/hooks/framework_django.py", line 427, in **call**
   return self.__wrapped(_args, *_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 47, in view
   return self.dispatch(request, _args, *_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in dispatch
   return handler(request, _args, *_kwargs)

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/views.py", line 210, in get
   client.complete(dict(request.GET.items()))

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/clients/oauth.py", line 285, in complete
   return self.get_access_token(code=GET.get('code'))

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/clients/oauth.py", line 273, in get_access_token
   self._access_token = self._get_access_token(code, **params)['access_token']

KeyError: 'access_token'

**Comment by flashingpumpkin** [comment]
This should provide a bit more insight what fetching the access token returns.

**Comment by flashingpumpkin** [comment]
The error is now caught and reraised as an `OAuthError` and displayed to the user.
