### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4352: ordinal not in range(128)

### ISSUE THREAD

**Issue by diafygi** [flashingpumpkin/django-socialregistration#135]
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 47, in view
   return self.dispatch(request, _args, *_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in dispatch
   return handler(request, _args, *_kwargs)

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/views.py", line 171, in post
   return HttpResponseRedirect(client.get_redirect_url())

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/clients/oauth.py", line 146, in get_redirect_url
   'oauth_token': self.get_request_token().key,

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/clients/oauth.py", line 126, in get_request_token
   self._request_token = self._get_request_token()

 File "/home/user/python-manual-installs/src/socialregistration/socialregistration/clients/oauth.py", line 94, in _get_request_token
   response['status'], self.request_token_url, content))

 File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 227, in **mod**
   return unicode(self) % rhs

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4352: ordinal not in range(128)

 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:8.0.1) Gecko/20100101 Firefox/8.0.1',

**Comment by flashingpumpkin** [comment]
This looks like `python-oauth2` is not returning a unicode string for the content. Possible?

**Comment by diafygi** [comment]
When we've seen this other places, wrapping with a smart_str() or smart_unicode() usually works

https://docs.djangoproject.com/en/dev/ref/unicode/#conversion-functions
